nasisi_trust/config/routes.rb
Rails.application.routes.draw do
  resources :beneficiaries
  devise_for :users
  root 'home#index'
end

nasisi_trust/app/models/beneficiary.rb
class Beneficiary < ActiveRecord::Base
end

nasisi_trust/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

nasisi_trust/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

nasisi_trust/app/controllers/beneficiaries_controller.rb
class BeneficiariesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_beneficiary, only: [:show, :edit, :update, :destroy]

  # GET /beneficiaries
  # GET /beneficiaries.json
  def index
    @beneficiaries = Beneficiary.all
  end

  # GET /beneficiaries/1
  # GET /beneficiaries/1.json
  def show
  end

  # GET /beneficiaries/new
  def new
    @beneficiary = Beneficiary.new
  end

  # GET /beneficiaries/1/edit
  def edit
  end

  # POST /beneficiaries
  # POST /beneficiaries.json
  def create
    @beneficiary = Beneficiary.new(beneficiary_params)

    respond_to do |format|
      if @beneficiary.save
        format.html { redirect_to @beneficiary, notice: 'Beneficiary was successfully created.' }
        format.json { render :show, status: :created, location: @beneficiary }
      else
        format.html { render :new }
        format.json { render json: @beneficiary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beneficiaries/1
  # PATCH/PUT /beneficiaries/1.json
  def update
    respond_to do |format|
      if @beneficiary.update(beneficiary_params)
        format.html { redirect_to @beneficiary, notice: 'Beneficiary was successfully updated.' }
        format.json { render :show, status: :ok, location: @beneficiary }
      else
        format.html { render :edit }
        format.json { render json: @beneficiary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beneficiaries/1
  # DELETE /beneficiaries/1.json
  def destroy
    @beneficiary.destroy
    respond_to do |format|
      format.html { redirect_to beneficiaries_url, notice: 'Beneficiary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beneficiary
      @beneficiary = Beneficiary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beneficiary_params
      params.require(:beneficiary).permit(:names, :string, :age, :integer, :gender, :string, :school, :string, :area, :string, :bio_data, :string)
    end
end

nasisi_trust/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

nasisi_trust/app/helpers/application_helper.rb
module ApplicationHelper
end

nasisi_trust/app/helpers/beneficiaries_helper.rb
module BeneficiariesHelper
end

nasisi_trust/app/helpers/home_helper.rb
module HomeHelper
end

nasisi_trust/app/views/beneficiaries/_form.html.haml
:css
  .top{
    margin-top: 5%;
  }
.top
  .ui.container
    .ui.grid
      .ten.wide.column.centered
        .ui.segment
          .ui.form
            = form_for(@beneficiary) do |f|
              - if @beneficiary.errors.any?
                #error_explanation
                  %h2
                    = pluralize(@beneficiary.errors.count, "error")
                    prohibited this beneficiary from being saved:
                  %ul
                    - @beneficiary.errors.full_messages.each do |message|
                      %li= message
              .field
                = f.label :names
                %br/
                = f.text_field :names

              .field
                .ui.grid
                  .eight.wide.column
                    .field
                      = f.label :age
                      %br/
                      = f.text_field :age
                  .eight.wide.column
                    .field
                      = f.label :gender
                      %br/
                      = f.text_field :gender

              .field
                = f.label :school
                %br/
                = f.text_field :school
              .field
                = f.label :area
                %br/
                = f.text_field :area
              .field
                = f.label :bio_data
                %br/
                = f.text_field :bio_data
              .actions
                = f.submit class: 'ui button'

nasisi_trust/app/views/beneficiaries/edit.html.haml
%h1 Editing Beneficiary
= render 'form'
= link_to 'Show', @beneficiary
|
= link_to 'Back', beneficiaries_path

nasisi_trust/app/views/beneficiaries/index.html.haml
%p#notice= notice
%h1 Listing Beneficiaries

%table.ui.celled.table
  %thead
    %tr
      %th Names
      %th Age
      %th Gender
      %th School
      %th Area
      %th Bio Data
      %th Action

  %tbody
    - @beneficiaries.each do |beneficiary|
      %tr
        %td= beneficiary.names
        %td= beneficiary.age
        %td= beneficiary.gender
        %td= beneficiary.school
        %td= beneficiary.area
        %td= beneficiary.bio_data
        %td
          = link_to 'Show', beneficiary
          |
          = link_to 'Edit', edit_beneficiary_path(beneficiary)
          |
          = link_to 'Destroy', beneficiary, method: :delete, data: { confirm: 'Are you sure?' }

  %tfoot
    %tr
      %th{colspan: '8'}
        .ui.right.floated.pagination.menu
          =link_to new_beneficiary_path do
            .ui.green.button
              New

/ %table
/   %thead
/     %tr
/       %th Names
/       %th Age
/       %th Gender
/       %th School
/       %th Area
/       %th Bio data
/       %th{:colspan => "3"}
/   %tbody
/     - @beneficiaries.each do |beneficiary|
/       %tr
/         %td= beneficiary.names
/         %td= beneficiary.age
/         %td= beneficiary.gender
/         %td= beneficiary.school
/         %td= beneficiary.area
/         %td= beneficiary.bio_data
/         %td= link_to 'Show', beneficiary
/         %td= link_to 'Edit', edit_beneficiary_path(beneficiary)
/         %td= link_to 'Destroy', beneficiary, method: :delete, data: { confirm: 'Are you sure?' }
/ %br/
/ = link_to 'New Beneficiary', new_beneficiary_path

nasisi_trust/app/views/beneficiaries/new.html.haml
%h1 New Beneficiary
= render 'form'
/= link_to 'Back', beneficiaries_path

nasisi_trust/app/views/beneficiaries/show.html.haml
%p#notice= notice
%p
  %strong Names:
  = @beneficiary.names

%p
  %strong Age:
  = @beneficiary.age

%p
  %strong Gender:
  = @beneficiary.gender

%p
  %strong School:
  = @beneficiary.school

%p
  %strong Area:
  = @beneficiary.area

%p
  %strong Bio data:
  = @beneficiary.bio_data

= link_to 'Edit', edit_beneficiary_path(@beneficiary)
|
= link_to 'Back', beneficiaries_path

nasisi_trust/app/views/home/index.html.haml
:css
	.top{
		margin-top: 5em;
	}
-if user_signed_in?
	%h2 Welcome, 
	= current_user.email
	/ = link_to 'logout', destroy_user_session_path, method: :delete
	-#.top
		-#%h4 Choose Platform of Choice
		-#.ui.grid
			-#.eight.wide.column
				-#.ui.center.aligned.segment
					
			-#.eight.wide.column
				-#.ui.center.aligned.segment
-else
	/ %h1 Home#index
	/ %p Find me in app/views/home/index.html.erb
	.ui.center.aligned.container
		= image_tag 'huipalas.jpg', height: '800'

nasisi_trust/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title NasisiTrust
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  :css
      body{
        height: 0px;
      }
  %body
    .ui.container
      .ui.secondary.pointing.menu
        =link_to 'Home', root_path, class: 'active item'
        -if user_signed_in?
          =link_to 'Beneficiaries', beneficiaries_path, class: 'item'
          =link_to 'Sponsors', '', class: 'item'
          =link_to 'Programs', '', class: 'item'
        .right.menu
          -if user_signed_in?
            =link_to 'Settings', edit_user_registration_path, class: 'ui item'
            =link_to 'Logout', destroy_user_session_path, method: :delete, class: 'ui item'
          -else
            = link_to 'login', new_user_session_path, class: 'ui item'
            = link_to 'Register', new_user_registration_path, class: 'ui item'

    .ui.container
      %p.notice
        = notice
      %p.alert
        = alert
      
      = yield